### ISSUE TITLE
Incorrect Skill Cost calculation

### ISSUE THREAD

**Issue by MistressAshai** [cecilbowen/galleriaclassbuilder#2]
The way discounts are calculated now are giving incorrect values.

Using Revolution's Chance as an example.

In-Game:
![image](https://user-images.githubusercontent.com/8222603/222032577-51af14df-471b-4c9f-b6b4-f79f564b6d4a.png)

`cost = Math.round(skill.cost * (1 - discount))`
cost = Math.round(30 * (1 - 0.66))
cost = Math.round(30 * (0.34))
cost = Math.round(10.2)
cost = 10

Builder:
![image](https://user-images.githubusercontent.com/8222603/222032689-42d67a93-9bbd-4a54-9563-302f474f43cc.png)

`cost = skill.cost - Math.floor(discount * skill.cost)`
cost = 30 - Math.floor(0.66 * 30)
cost = 30 - Math.floor(19.8)
cost = 30 - 19
cost = 11

And in the inverse case, where the value before rounding is 10.5 or higher, the game would round up to 11 instead of 10.

**Comment by MistressAshai** [comment]
But, this also seem to be proven wrong by Tenacious Speed being a cost of 10 becoming 4...

Edit: Thin Ice's cost of 4 becomes...2?

**Comment by cecilbowen** [comment]
Your fix involving Math.round in your recent PR seemed to work for most skills, but I noticed "Lone Ranger" displayed incorrectly with it.  I pushed up a [change ](https://github.com/cecilbowen/galleriaclassbuilder/commit/7c599fb9642b2480ff9ad8de2e8fe96020276028)to make it Math.ceil instead and it seems to work for all the cases I've tried.  Let me know if you see otherwise.

**Comment by MistressAshai** [comment]
Yeah, that's what I meant with Math.round. For _most_ skills, it'll be fine, but some outliers just seem to ignore proper rounding rules in-game?
Here are the in-game costs using this build:
`6_42-270-103-208-91-312-131-220-324-158-94-98-321-99-315-102-271-96-92-218-160-21-272-90-16-149-104-95_999`

![image](https://user-images.githubusercontent.com/8222603/222123806-e56ea624-810c-40c6-981e-11f193b91471.png)
![image](https://user-images.githubusercontent.com/8222603/222123924-d6c7cc71-ca0c-4439-9bc6-9af6185d9d51.png)
![image](https://user-images.githubusercontent.com/8222603/222124013-ed48daa8-4b36-4555-9b4b-a819193f1f9f.png)

The notable skills that are incorrect here when using Math.ceil are:
- Revolution's Chance [10] -66%
- Cubelia [18] -66%
- Blind Spot Passage [1] -66%

**Comment by cecilbowen** [comment]
I was really hoping it was us and not the game's poor rounding, but, it looks like you're right.  I can't seem to find a consistent method.  I guess most accurate way would be to add `initialCost` and `classCost` fields for *every* skill.  That's a lot of effort, though.

**Comment by MistressAshai** [comment]
Could just stick with Math.round and only add initial/class costs for the outliers

**Comment by cecilbowen** [comment]
Not a bad idea.  I'll probably swap to Math.round, and then end up using `getSkillDiscountedCost` on all the skills to set default initial/class costs on all the skills.  Then the outliers can be updated as they are found.

**Comment by cecilbowen** [comment]
Since the outliers are consistent (eg. every 29 base skill cost skill with a class discount ends up costing 10) I ended up adding a `skill-cost.json` file ([in this commit](https://github.com/cecilbowen/galleriaclassbuilder/commit/1a99505b73114ed6f89f9c48b7bbb91fe0873fb3)) that contains a map with the base skill costs and their associated initial and class cost discounts.  This file covers all the base skill costs, and is only missing 3 skill cost tiers -- 28 (Gifted), 53 (Asceticism, Double Wide) and 70 (Eclipse, Stargazer) -- because I have not yet gotten a character with those three class-discounted skills.

**Comment by MistressAshai** [comment]
I can check on those skills later today

**Comment by MistressAshai** [comment]
For class costs, it is:

28 (Gifted) - 10
53 (Asceticism, Double Wide) - 18
70 (Eclipse, Stargazer) - 24

**Comment by cecilbowen** [comment]
Thanks, I've updated with these changes.
